name: food_recipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  json_annotation: ^4.9.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/gps.png
    - assets/icons/home.png
    - assets/icons/home-fill.png
    - assets/icons/saved.png
    - assets/icons/saved-fill.png
    - assets/icons/notification.png
    - assets/icons/notification-fill.png
    - assets/icons/profile.png
    - assets/icons/profile-fill.png
    - assets/icons/inactive.png
    - assets/icons/timer.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/avatar.png
    - assets/icons/search.png
    - assets/icons/setting.png
    - assets/images/tomato.png
    - assets/images/cat.jpeg
    - assets/images/salmon.jpg
    - assets/images/acai.jpg
    - assets/images/avo.jpg
    - assets/images/banana.jpg
    - assets/images/egg.jpeg
    - assets/images/fish.jpg
    - assets/images/octopus.jpeg        

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
